name: BlablaBook
services:
  api:
    build:
      context: ./api
    ports:
      - 3000:3000
    depends_on:
      - db
    container_name: blablabook-api
    env_file:
      - .docker.env
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./api/package.json
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - 5173:5173
    depends_on:
      - api
    container_name: blablabook-client
    env_file:
      - .docker.env
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
  db:
    image: postgres:18-alpine
    container_name: blablabook-database
    env_file:
      - .docker.env
    volumes:
      - ./api/data:/docker-entrypoint-initdb.d
      - pg-blablabook:/var/lib/postgresql/data
volumes:
  pg-blablabook: